version: '3'
services:
  scala:
    build: ./docker/scala
    tty: true
    volumes: [".:/opt/scala"]
    ports:
      - 9000:9000
    working_dir: /opt/scala
    command: /bin/bash -c "source /root/.sdkman/bin/sdkman-init.sh && sbt run"
  db:
    image: 'arm64v8/mysql:8.0-oracle'
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'juge6'  
        MYSQL_USER: docker_user
        MYSQL_PASSWORD: docker_pass
    volumes:  
        - './docker/mysql:/var/lib/mysql'
    healthcheck:  
        test: ["CMD", "mysqladmin", "ping"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=docker_user
      - PMA_PASSWORD=docker_pass
    ports:
      - "3096:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions